controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Joint Trajectory Controller
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Joint State Broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Velocity Controller
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    # Effort Controller
    effort_controller:
      type: effort_controllers/JointGroupEffortController

# Joint Trajectory Controller Parameters
joint_trajectory_controller:
  ros__parameters:
    joints:
      - FR_calf_joint
      - FR_hip_joint
      - FR_thigh_joint
      - RR_hip_joint
      - RR_calf_joint
      - FL_thigh_joint
      - FL_calf_joint
      - RL_hip_joint
      - RR_thigh_joint
      - RL_thigh_joint
      - FL_hip_joint
      - RL_calf_joint

    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    # gains:
    #   FR_hip_joint:
    #     p: 100.0
    #     i: 0.01
    #     d: 10.0
    #   FR_thigh_joint:
    #     p: 100.0
    #     i: 0.01
    #     d: 10.0
    #   FR_calf_joint:
    #     p: 100.0
    #     i: 0.01
    #     d: 10.0
    #   FL_hip_joint:
    #     p: 100.0
    #     i: 0.01
    #     d: 10.0
    #   FL_thigh_joint:
    #     p: 100.0
    #     i: 0.01
    #     d: 10.0
    #   FL_calf_joint:
    #     p: 100.0
    #     i: 0.01
    #     d: 10.0
    #   RR_hip_joint:
    #     p: 100.0
    #     i: 0.01
    #     d: 10.0
    #   RR_thigh_joint:
    #     p: 100.0
    #     i: 0.01
    #     d: 10.0
    #   RR_calf_joint:
    #     p: 100.0
    #     i: 0.01
    #     d: 10.0
    #   RL_hip_joint:
    #     p: 100.0
    #     i: 0.01
    #     d: 10.0
    #   RL_thigh_joint:
    #     p: 100.0
    #     i: 0.01
    #     d: 10.0
    #   RL_calf_joint:
    #     p: 100.0
    #     i: 0.01
    #     d: 10.0

# Joint State Broadcaster Parameters
joint_state_broadcaster:
  ros__parameters:
    joints:
      - FR_calf_joint
      - FR_hip_joint
      - FR_thigh_joint
      - RR_hip_joint
      - RR_calf_joint
      - FL_thigh_joint
      - FL_calf_joint
      - RL_hip_joint
      - RR_thigh_joint
      - RL_thigh_joint
      - FL_hip_joint
      - RL_calf_joint

# Velocity Controller Parameters
velocity_controller:
  ros__parameters:
    joints:
      - FR_calf_joint
      - FR_hip_joint
      - FR_thigh_joint
      - RR_hip_joint
      - RR_calf_joint
      - FL_thigh_joint
      - FL_calf_joint
      - RL_hip_joint
      - RR_thigh_joint
      - RL_thigh_joint
      - FL_hip_joint
      - RL_calf_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    # gains:
    #   FR_hip_joint:
    #     p: 50.0
    #     i: 0.01
    #     d: 5.0
    #   FR_thigh_joint:
    #     p: 50.0
    #     i: 0.01
    #     d: 5.0
    #   FR_calf_joint:
    #     p: 50.0
    #     i: 0.01
    #     d: 5.0
    #   FL_hip_joint:
    #     p: 50.0
    #     i: 0.01
    #     d: 5.0
    #   FL_thigh_joint:
    #     p: 50.0
    #     i: 0.01
    #     d: 5.0
    #   FL_calf_joint:
    #     p: 50.0
    #     i: 0.01
    #     d: 5.0
    #   RR_hip_joint:
    #     p: 50.0
    #     i: 0.01
    #     d: 5.0
    #   RR_thigh_joint:
    #     p: 50.0
    #     i: 0.01
    #     d: 5.0
    #   RR_calf_joint:
    #     p: 50.0
    #     i: 0.01
    #     d: 5.0
    #   RL_hip_joint:
    #     p: 50.0
    #     i: 0.01
    #     d: 5.0
    #   RL_thigh_joint:
    #     p: 50.0
    #     i: 0.01
    #     d: 5.0
    #   RL_calf_joint:
    #     p: 50.0
    #     i: 0.01
    #     d: 5.0

# Effort Controller Parameters
effort_controller:
  ros__parameters:
    joints:
      - FR_calf_joint
      - FR_hip_joint
      - FR_thigh_joint
      - RR_hip_joint
      - RR_calf_joint
      - FL_thigh_joint
      - FL_calf_joint
      - RL_hip_joint
      - RR_thigh_joint
      - RL_thigh_joint
      - FL_hip_joint
      - RL_calf_joint
    interface_name: effort
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    # gains:
    #   FR_hip_joint:
    #     p: 200.0
    #     i: 0.1
    #     d: 20.0
    #   FR_thigh_joint:
    #     p: 200.0
    #     i: 0.1
    #     d: 20.0
    #   FR_calf_joint:
    #     p: 200.0
    #     i: 0.1
    #     d: 20.0
    #   FL_hip_joint:
    #     p: 200.0
    #     i: 0.1
    #     d: 20.0
    #   FL_thigh_joint:
    #     p: 200.0
    #     i: 0.1
    #     d: 20.0
    #   FL_calf_joint:
    #     p: 200.0
    #     i: 0.1
    #     d: 20.0
    #   RR_hip_joint:
    #     p: 200.0
    #     i: 0.1
    #     d: 20.0
    #   RR_thigh_joint:
    #     p: 200.0
    #     i: 0.1
    #     d: 20.0
    #   RR_calf_joint:
    #     p: 200.0
    #     i: 0.1
    #     d: 20.0
    #   RL_hip_joint:
    #     p: 200.0
    #     i: 0.1
    #     d: 20.0
    #   RL_thigh_joint:
    #     p: 200.0
    #     i: 0.1
    #     d: 20.0
    #   RL_calf_joint:
    #     p: 200.0
    #     i: 0.1
    #     d: 20.0